77 amount zero
hodlwallet/hodlwallet pull request #88
Opened 2022-01-12 21:41 UTC by Jonathan-G555

### Summary

These changes are oriented to make the app more friendly with the user. Previously, when the app loaded the HomeView, it used to show the amount balance equal to zero, and it make the loading of the correct amount only after executing the OnAppearing method, this happens for example after changing to another tab and returning to HomeView.

So, it was necessary to add the instruction to assign the amount to the Balance property without the necessity to use the OnAppearing method, this was made with the addition of the assignation of the balance in the WalletService_OnStarted method at the HomeViewModel.

After that, the balance is equal to zero when the view is showed and only changes to the correct amount after some moments, when the service is loaded, therefore it is better to hide the zero value until the right balance is loaded.

This was made changing the visibility of the Balance to false when HomeView is loaded and returning it to true value after loading the right balance, this is made through the BalanceLabelToVisible method.

2022-01-13 00:01 UTC, igorgue requested changes
@Jonathan-G555 I'm not sure if I like your solution, isn't it better to set the Label to `""` or `string.Empty` if the wallet hasn't loaded yet?

And in general, do we think is a big problem to see 0?

Sorry if I didn't say it before, I'm just thinking now it's actually not a big deal, I thought initially the bug was a bit different (you had transactions and it was showing 0)

2022-01-13 14:57 UTC, Jonathan-G555 commented
I think that is important do not show a zero in the amount even if it is for a short time, imagine you have 5 BTC in your wallet and you watch a zero instead, what if there are not connection and it is not posible update the real amount... I think that this could be terrifying to the user, and it is not difficult to avoid it.

2022-01-13 16:31 UTC, Jonathan-G555 commented
About setting the label to empty, that is exactly the first thing that I tried, but there is a binding between the label and the Balance property. So, if a new value is assigned to the label, the binding is broken.

In that case, it would be necessary to assign a value to the property to change the label, but this takes some time, because of the wallet service. So, it is easier only to make the label invisible until the current amount is gotten.

Additionally, the balance property has a zero value at first because it is a decimal variable, this type has the value 0 by defect.

2022-01-13 17:20 UTC, igorgue commented
@Jonathan-G555 Yeah but I rather show something that says "Loading..." instead of right now that shows " BTC" like something is missing.

On the other hand, if the wallet is already synced there's no reason why we wouldn't have saved that balance in somewhere, you could investigate that.

2022-01-13 17:25 UTC, igorgue commented
@Jonathan-G555 the account also have transactions and unspent coins so there's no reason why you couldn't run `GetAccount()` instead of the way it's calculated right now...

2022-01-18 17:37 UTC, igorgue commented
@Jonathan-G555 Did you continue researching this?

2022-01-19 14:50 UTC, Jonathan-G555 commented
There is a property called BalanceFiat in HomeViewModel that is related with the changing of currency, because it changes with the rate, but this property is never used. This is why the change of currency does not have effect in the Balance label.

I think that BalanceFiat could be eliminated to start using the Balance property instead. What do you think?

2022-01-19 20:14 UTC, igorgue commented
> Well, the rate is always equal to zero, maybe because it is testnet.

On testnet we should show the same rate, but you should research that too :)

> There is a property called BalanceFiat in HomeViewModel that is related with the changing of currency, because it changes with the rate, but this property is never used.

I'm not sure, but could the idea be that the `Balance` is the balance in BTC while the `BalanceFiat` is the balance on USD?

> I think that BalanceFiat will be eliminated to start using the Balance property instead. Am I right?

I don't understand... *will be eliminated* by who? Do you mean *could be*? Also, I think it's up to you guys to decide how this would work @marconipoveda should be working on currency settings.

2022-01-19 20:17 UTC, igorgue commented
@Jonathan-G555 In general though, I don't like this solution, we're not trying to hide our problems but rather fix them.

2022-01-19 20:17 UTC, closed without merging